
'use client';
import { useState, useRef } from 'react';
import KnowledgeMatchCard from './KnowledgeMatchCard';

export default function DocAnalyzer() {
  const [file, setFile] = useState<File | null>(null);
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [exporting, setExporting] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const analyze = async () => {
    if (!file || loading) return;
    setLoading(true);
    setResult(null);
    const fd = new FormData();
    fd.append('file', file);
    fd.append('question', question || 'Summarize this document clinically');
    try {
      const res = await fetch('/api/analyze-doc', { method: 'POST', body: fd });
      const data = await res.json();
      setResult(data);
    } catch {
      setResult({ error: 'Analysis failed — please try again' });
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    if (!printRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${result?.filename || 'Cliniverse Analysis'}</title>
          <style>
            body { font-family: -apple-system, sans-serif; padding: 32px; color: #0F172A; }
            h1 { font-size: 18px; color: #0D9488; margin-bottom: 4px; }
            .meta { font-size: 11px; color: #94A3B8; margin-bottom: 20px; }
            .content { font-size: 13px; line-height: 1.7; white-space: pre-wrap; }
            .disclaimer { margin-top: 20px; padding: 10px 14px; background: #F0FDF9; border-radius: 8px; font-size: 10px; color: #047857; }
          </style>
        </head>
        <body>
          <h1>📄 ${result?.filename || 'Document'} — Clinical Analysis</h1>
          <div class="meta">Generated by Cliniverse AI · ${new Date().toLocaleDateString()}</div>
          <div class="content">${(result?.analysis || '').replace(/</g, '&lt;')}</div>
          <div class="disclaimer">⚠️ Educational use only. Verify all clinical information independently.</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 250);
  };

  const handleDownloadPDF = async () => {
    if (!result?.analysis) return;
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      doc.setFontSize(14);
      doc.setTextColor(13, 148, 136); // teal
      doc.text(`${result.filename || 'Document'} — Clinical Analysis`, 14, 18);

      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184); // muted
      doc.text(`Generated by Cliniverse AI · ${new Date().toLocaleDateString()}`, 14, 25);

      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42); // primary text
      const lines = doc.splitTextToSize(result.analysis, 180);
      doc.text(lines, 14, 36);

      const finalY = 36 + lines.length * 5 + 10;
      doc.setFontSize(8);
      doc.setTextColor(4, 120, 87);
      doc.text('Educational use only. Verify all clinical information independently.', 14, finalY);

      doc.save(`${(result.filename || 'analysis').replace(/\.[^.]+$/, '')}_cliniverse.pdf`);
    } catch (e) {
      alert('PDF export failed — please try Print instead.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div style={{
      padding: '20px 16px 100px',
      fontFamily: '-apple-system, "SF Pro Display", sans-serif',
      minHeight: '100vh',
      background: '#F8FAFC',
    }}>
      <div style={{ fontSize: 24, fontWeight: 800, color: '#0F172A', marginBottom: 4 }}>
        📄 Document Analyzer
      </div>
      <div style={{ fontSize: 13, color: '#64748B', marginBottom: 20 }}>
        Upload any medical PDF or document — AI extracts clinical insights instantly
      </div>

      {/* Upload Card */}
      <div style={{
        background: '#FFFFFF', borderRadius: 20, padding: 20,
        border: '1px solid #E2E8F0', marginBottom: 16,
        boxShadow: '0 2px 12px rgba(15,23,42,0.06)',
      }}>
        <div
          onClick={() => fileRef.current?.click()}
          style={{
            border: `2px dashed ${file ? '#0D9488' : '#CBD5E1'}`,
            borderRadius: 16, padding: 32, textAlign: 'center',
            cursor: 'pointer', background: file ? '#F0FDF9' : '#F8FAFC',
            transition: 'all 0.2s',
          }}>
          <div style={{ fontSize: 40 }}>{file ? '📋' : '📤'}</div>
          <div style={{ fontSize: 14, fontWeight: 600, color: '#0F172A', marginTop: 8 }}>
            {file ? file.name : 'Tap to upload document'}
          </div>
          <div style={{ fontSize: 12, color: '#94A3B8', marginTop: 4 }}>
            PDF, DOCX, TXT — Discharge summaries, Guidelines, Reports
          </div>
        </div>
        <input
          ref={fileRef} type="file" accept=".pdf,.docx,.doc,.txt"
          style={{ display: 'none' }}
          onChange={e => setFile(e.target.files?.[0] || null)}
        />

        <input
          style={{
            width: '100%', padding: '10px 14px', marginTop: 12,
            border: '1px solid #E2E8F0', borderRadius: 12,
            fontSize: 14, outline: 'none', fontFamily: 'inherit',
            boxSizing: 'border-box' as const,
          }}
          placeholder="Optional: Ask a specific question about the document..."
          value={question}
          onChange={e => setQuestion(e.target.value)}
        />

        <button
          onClick={analyze}
          disabled={!file || loading}
          style={{
            width: '100%', padding: 14, marginTop: 12,
            background: !file || loading
              ? '#E2E8F0'
              : 'linear-gradient(135deg, #0D9488, #1E40AF)',
            color: !file || loading ? '#94A3B8' : '#FFFFFF',
            border: 'none', borderRadius: 14,
            fontSize: 15, fontWeight: 700, cursor: !file || loading ? 'not-allowed' : 'pointer',
          }}>
          {loading ? '⏳ Analyzing…' : '🔬 Analyze Document'}
        </button>
      </div>

      {result?.error && (
        <div style={{
          background: '#FEE2E2', borderRadius: 14, padding: 16,
          color: '#991B1B', fontSize: 13,
        }}>
          ❌ {result.error}
        </div>
      )}

      {result?.analysis && (
        <>
          <div ref={printRef} style={{
            background: '#FFFFFF', borderRadius: 20, padding: 20,
            border: '1px solid #E2E8F0', marginBottom: 14,
          }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#0D9488', marginBottom: 12 }}>
              ✅ {result.filename} — Analysis Complete
            </div>
            <div style={{ fontSize: 14, color: '#0F172A', lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>
              {result.analysis}
            </div>
            <div style={{
              marginTop: 12, padding: '8px 12px',
              background: '#F0FDF9', borderRadius: 10,
              fontSize: 11, color: '#047857',
            }}>
              ⚠️ Educational use only. Verify all clinical information independently.
            </div>
          </div>

          {/* Export actions */}
          <div style={{ display: 'flex', gap: 10, marginBottom: 14 }}>
            <button
              onClick={handlePrint}
              style={{
                flex: 1, padding: 12, borderRadius: 14,
                border: '1px solid #E2E8F0', background: '#FFFFFF',
                color: '#0F172A', fontSize: 13, fontWeight: 700,
                cursor: 'pointer', display: 'flex', alignItems: 'center',
                justifyContent: 'center', gap: 6,
              }}>
              🖨️ Print
            </button>
            <button
              onClick={handleDownloadPDF}
              disabled={exporting}
              style={{
                flex: 1, padding: 12, borderRadius: 14,
                border: 'none',
                background: exporting ? '#E2E8F0' : 'linear-gradient(135deg, #0D9488, #1E40AF)',
                color: exporting ? '#94A3B8' : '#FFFFFF',
                fontSize: 13, fontWeight: 700,
                cursor: exporting ? 'not-allowed' : 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
              }}>
              {exporting ? '⏳ Preparing…' : '⬇️ Download PDF'}
            </button>
          </div>

          {/* Knowledge Graph — surfaces similar past cases based on this
              document's analysis text. */}
          <KnowledgeMatchCard queryText={result.analysis} />
        </>
      )}
    </div>
  );
}
