'use client'
import { useState } from 'react'
const S=[{id:'start',icon:'🚀',title:'Getting Started',color:'#00C4B4',steps:[{icon:'🎨',title:'Choose Theme',desc:'Pick Clinical White, Dark Cosmic, or Midnight Blue on first launch. Change in ME tab.'},{icon:'🔥',title:'Daily Streak',desc:'Complete one case daily to maintain streak and earn bonus XP.'}]},{id:'tools',icon:'🛠️',title:'TOOLS',color:'#bf5af2',steps:[{icon:'🌍',title:'Clinical Nexus',desc:'Join 1000+ doctors on same case globally. See real-time votes.'},{icon:'⚡',title:'Rapid Fire',desc:'30 questions in 3 minutes. Share score on WhatsApp.'},{icon:'🤖',title:'AI Generator',desc:'Unlimited custom cases by specialty. Powered by Claude AI.'},{icon:'🫀',title:'Surgical AI',desc:'Cardiac, Neuro, General Surgery protocols with live AI Consultant.'}]},{id:'pro',icon:'🚀',title:'Pro',color:'#ffd60a',steps:[{icon:'🔓',title:'Free',desc:'1 case per module, Daily Challenge, Quick Reference — forever free.'},{icon:'⭐',title:'Pro',desc:'Unlimited cases, all modules, Clinical Nexus, AI Generator.'},{icon:'💳',title:'Subscribe',desc:'ME tab → Upgrade to Pro → Apple Pay or Card. Cancel anytime.'}]}]
interface P{onClose:()=>void;onUpgrade?:()=>void}
export default function UserGuide({onClose,onUpgrade}:P){
  const [a,setA]=useState<string|null>(null)
  const sec=S.find(s=>s.id===a)
  const H=({onBack,title,children}:{onBack:()=>void,title:string,children:React.ReactNode})=>(
    <div style={{fontFamily:'-apple-system,sans-serif',background:'#1e3d52',minHeight:'100vh'}}>
      <div style={{background:'rgba(36,63,82,0.60)',padding:'12px 20px',display:'flex',alignItems:'center',gap:12,borderBottom:'1px solid rgba(36,63,82,0.65)',position:'sticky',top:0}}>
        <button onClick={onBack} style={{background:'none',border:'none',color:'#00C4B4',fontSize:16,cursor:'pointer',fontWeight:600}}>← Back</button>
        <span style={{fontWeight:700,fontSize:16,color:'white'}}>{title}</span>
      </div>
      <div style={{padding:20}}>{children}</div>
    </div>
  )
  if(a&&sec)return(<H onBack={()=>setA(null)} title={sec.icon+' '+sec.title}>{sec.steps.map((st,i)=>(<div key={i} style={{background:'rgba(36,63,82,0.60)',borderRadius:20,padding:18,marginBottom:14,border:`1px solid ${sec.color}20`}}><div style={{display:'flex',gap:12}}><div style={{width:44,height:44,borderRadius:14,background:`${sec.color}18`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:22,flexShrink:0}}>{st.icon}</div><div><div style={{fontSize:15,fontWeight:700,color:'white',marginBottom:4}}>{st.title}</div><div style={{fontSize:14,color:'rgba(255,255,255,0.65)',lineHeight:1.7}}>{st.desc}</div></div></div></div>))}{sec.id==='pro'&&onUpgrade&&<button onClick={onUpgrade} style={{width:'100%',padding:16,borderRadius:18,border:'none',background:'linear-gradient(135deg,#ffd60a,#ff9f0a)',color:'black',fontSize:15,fontWeight:800,cursor:'pointer'}}>🚀 Upgrade to Pro</button>}</H>)
  return(<div style={{fontFamily:'-apple-system,sans-serif',background:'#1e3d52',minHeight:'100vh'}}><div style={{background:'rgba(36,63,82,0.60)',padding:'12px 20px',display:'flex',alignItems:'center',gap:12,borderBottom:'1px solid rgba(36,63,82,0.65)',position:'sticky',top:0}}><button onClick={onClose} style={{background:'none',border:'none',color:'#00C4B4',fontSize:16,cursor:'pointer',fontWeight:600}}>← Close</button><span style={{fontWeight:700,fontSize:16,color:'white'}}>How to Use Cliniverse AI</span></div><div style={{padding:20}}><div style={{background:'linear-gradient(135deg,rgba(0,196,180,0.25),rgba(0,196,180,0.10))',borderRadius:22,padding:20,marginBottom:20,border:'1px solid rgba(139,92,246,0.3)',textAlign:'center'}}><div style={{fontSize:40,marginBottom:8}}>📖</div><div style={{fontSize:18,fontWeight:800,color:'white',marginBottom:4}}>Quick Guide</div><div style={{fontSize:13,color:'rgba(255,255,255,0.5)'}}>Everything to master Cliniverse AI</div></div>{S.map(s=>(<div key={s.id} onClick={()=>setA(s.


id)} style={{background:'rgba(36,63,82,0.60)',borderRadius:18,padding:16,marginBottom:12,border:`1px solid ${s.color}20`,cursor:'pointer',display:'flex',alignItems:'center',gap:14}}><div style={{width:48,height:48,borderRadius:15,background:`${s.color}18`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:24,flexShrink:0}}>{s.icon}</div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700,color:'white'}}>{s.title}</div><div style={{fontSize:12,color:'rgba(255,255,255,0.4)',marginTop:2}}>{s.steps.length} topics</div></div><span style={{color:'rgba(255,255,255,0.3)',fontSize:20}}>›</span></div>))}</div></div>)
}
