import test from 'node:test'
import assert from 'node:assert/strict'
import { createEchoAccountEventRepository, EchoStorageUnavailable } from '../app/lib/competency/echoAccountEventRepository.ts'
const A='00000000-0000-4000-8000-000000000001'
const row=(id)=>({event_id:id,user_id:A,case_id:'a4c',task_id:'view',task_version:'1',skill_id:'skill',selected_answer:'a',normalized_score:100,confidence:3,response_time_ms:500,observed_at:'2026-09-13T12:00:00Z',created_at:'2026-09-13T12:00:01.123456Z'})
function fixture(rows,error=null){const calls=[];let owner=A;const client={auth:{async getUser(){return {data:{user:{id:owner}},error:null}}},from(table){calls.push(['from',table]);const q={select(){return q},eq(k,v){calls.push(['eq',k,v]);return q},order(k,v){calls.push(['order',k,v]);return q},limit(v){calls.push(['limit',v]);return q},or(v){calls.push(['or',v]);return q},then(resolve,reject){return Promise.resolve({data:rows,error}).then(resolve,reject)}};return q}};return {repo:createEchoAccountEventRepository(client),calls,setOwner:v=>owner=v}}
test('history preserves microsecond cursor and never presents a partial page as full history',async()=>{const {repo,calls}=fixture([row('c'),row('b'),row('a')]);const page=await repo.historyPage(A,null,2);assert.equal(page.events.length,2);assert.deepEqual(page.nextCursor,{createdAt:'2026-09-13T12:00:01.123456Z',eventId:'b'});assert.ok(calls.some(x=>x[0]==='eq'&&x[1]==='user_id'&&x[2]===A))})
test('cursor values containing filter punctuation are quoted',async()=>{const {repo,calls}=fixture([]);const cursor={createdAt:'2026-09-13T12:00:01.123456Z',eventId:'id\",user_id.eq.other'};await repo.historyPage(A,cursor);assert.equal(calls.find(x=>x[0]==='or')[1],`created_at.lt.${JSON.stringify(cursor.createdAt)},and(created_at.eq.${JSON.stringify(cursor.createdAt)},event_id.lt.${JSON.stringify(cursor.eventId)})`)})
test('empty and unavailable histories remain distinct',async()=>{assert.deepEqual(await fixture([]).repo.historyPage(A),{events:[],nextCursor:null});await assert.rejects(fixture(null,{code:'PGRST205'}).repo.historyPage(A),EchoStorageUnavailable)})
test('foreign rows and wrong accounts are rejected',async()=>{await assert.rejects(fixture([{...row('x'),user_id:'foreign'}]).repo.historyPage(A));const f=fixture([]);f.setOwner('another');await assert.rejects(f.repo.historyPage(A));assert.equal(f.calls.length,0)})
