import test from 'node:test'
import assert from 'node:assert/strict'
import { buildXapiExport, echoStatement, ecgStatement } from '../app/lib/learningExport/xapi.ts'
const owner='00000000-0000-4000-8000-000000000001'
const echo=()=>({user_id:owner,event_id:'event-a',case_id:'a4c',task_id:'view',task_version:'1',skill_id:'view-recognition',normalized_score:90,confidence:3,response_time_ms:1500,observed_at:'2026-09-13T12:00:00Z',created_at:'2026-09-13T12:00:01Z'})
const ecg=()=>({user_id:owner,event_id:'event-b',case_id:'record10',decision_id:'a'.repeat(64),evidence_digest:'b'.repeat(64),decision_receipt:{decision:'LEARNER_ELIGIBLE',learnerReady:true,decisionId:'a'.repeat(64),evidenceDigest:'b'.repeat(64)},evidence:{userId:owner,eventId:'event-b',caseId:'record10',scoringVersion:'1.0.0',observedAt:'2026-09-13T12:00:02Z',attempt:{learnerId:owner,attemptId:'event-b',caseId:'record10',gateState:'LEARNER_ELIGIBLE'},result:{decision:'SCORED',overallScore:0.9,outcome:'FAIL',confidence:0.7}},created_at:'2026-09-13T12:00:03Z'})
test('Echo percent and duration map to xAPI without a mastery/success claim',()=>{const s=echoStatement(owner,echo());assert.equal(s.result.score.scaled,0.9);assert.equal(s.result.score.raw,90);assert.equal(s.result.duration,'PT1.5S');assert.equal('success' in s.result,false);assert.equal('completion' in s.result,false)})
test('statement UUID is deterministic and isolated by account/modality',()=>{const s=echoStatement(owner,echo());assert.match(s.id,/^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);assert.equal(s.id,echoStatement(owner,echo()).id);assert.notEqual(s.id,echoStatement('other',{...echo(),user_id:'other'}).id);assert.equal('mbox' in s.actor,false)})
test('ECG normalized score is not divided by 100 and critical-miss outcome is preserved',()=>{const s=ecgStatement(owner,ecg());assert.equal(s.result.score.scaled,0.9);assert.equal(s.result.extensions['https://cliniverseai.com/xapi/extensions/confidence'],0.7);assert.equal(s.result.extensions['https://cliniverseai.com/xapi/extensions/engine-outcome'],'FAIL');assert.equal('success' in s.result,false)})
test('ECG HOLD or receipt mismatch cannot become an exported assessment',()=>{for(const patch of [{decision:'HOLD'},{learnerReady:false},{decisionId:'wrong'}]){const row=ecg();Object.assign(row.decision_receipt,patch);assert.throws(()=>ecgStatement(owner,row))}})
test('foreign rows and missing persistence timestamps are rejected',()=>{assert.throws(()=>echoStatement('other',echo()));assert.throws(()=>echoStatement(owner,{...echo(),created_at:undefined}));assert.throws(()=>ecgStatement('other',ecg()))})
test('invalid scores, confidence and time fail closed',()=>{for(const patch of [{normalized_score:101},{normalized_score:NaN},{confidence:6},{observed_at:'bad'},{response_time_ms:-1}])assert.throws(()=>echoStatement(owner,{...echo(),...patch}))})
test('export is deterministic across row order and rejects duplicate identities',()=>{assert.deepEqual(buildXapiExport(owner,[echo()],[ecg()]),buildXapiExport(owner,[echo()],[ecg()]));assert.throws(()=>buildXapiExport(owner,[echo(),echo()],[]));assert.deepEqual(buildXapiExport(owner,[],[]),[])})
test('content versions use different activity IDs without leaking selected answers',()=>{const s=echoStatement(owner,{...echo(),selected_answer:'private answer'});assert.notEqual(s.object.id,echoStatement(owner,{...echo(),task_version:'2'}).object.id);assert.equal(JSON.stringify(s).includes('private answer'),false)})

import { createLearningExportHandler } from '../app/lib/learningExport/handler.ts'
function handler({user=owner,count=1,error=null,rows=[echo()]}={}) {
 const calls=[]
 const get=createLearningExportHandler(token=>({auth:{async getUser(t){calls.push(['auth',token,t]);return {data:{user:user?{id:user}:null},error:null}}},from(table){const q={select(){return q},eq(k,v){calls.push([k,v]);return q},order(){return q},limit(){return q},then(resolve){return Promise.resolve({data:table==='echo_competency_events'?rows:[],count:table==='echo_competency_events'?count:0,error}).then(resolve)}};return q}}))
 return {get,calls}
}
const request=()=>new Request('https://local/api/learning-export?user_id=foreign',{headers:{Authorization:'Bearer test-only'}})
test('missing token and invalid identity never query history',async()=>{const f=handler();assert.equal((await f.get(new Request('https://local'))).status,401);assert.equal(f.calls.length,0);const g=handler({user:null});assert.equal((await g.get(request())).status,401);assert.equal(g.calls.filter(c=>c[0]==='user_id').length,0)})
test('authenticated export binds both queries to verified owner, ignores requested owner and disables caching',async()=>{const f=handler();const r=await f.get(request());assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.equal((await r.json()).length,1);assert.equal(f.calls.filter(c=>c[0]==='user_id'&&c[1]===owner).length,2)})
test('server-capped history is rejected instead of exported as complete',async()=>{assert.equal((await handler({count:1001}).get(request())).status,413)})
test('database failures and foreign returned rows fail without leaking data',async()=>{for(const opts of [{error:{message:'internal'}},{rows:[{...echo(),user_id:'foreign'}]}]){const r=await handler(opts).get(request());assert.equal(r.status,503);assert.equal(JSON.stringify(await r.json()).includes('internal'),false)}})
