'use client'

import { Activity, ArrowLeft, CheckCircle2, Clock3, ShieldAlert } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import {
  DOOR_TO_ECG_MARKER_LEADS,
  DOOR_TO_ECG_SYNTHETIC_LEADS,
  matchesConfiguredMarker,
  type SyntheticLeadId,
} from '../../lib/cardiology/ecgWaveform'
import type { PathwayReplayReport, ReplayAgentState, ReplayIntegrityState } from '../../lib/cardiology/pathwayReplayAgents'
import styles from './pathway-replay.module.css'

interface Props {
  report: PathwayReplayReport
  labels: {
    back: string
    humanReview: string
    disclaimer: string
  }
}

type View = 'replay' | 'drill' | 'reassessment'

const agentLabels: Record<ReplayAgentState, string> = {
  complete: 'Complete', ready: 'Ready', 'human-review': 'Human review',
}

export default function PathwayReplayExperience({ report, labels }: Props) {
  const [view, setView] = useState<View>('replay')
  const [selectedLeads, setSelectedLeads] = useState<SyntheticLeadId[]>([])
  const [submitted, setSubmitted] = useState(false)
  const [drillComplete, setDrillComplete] = useState(false)
  const measuredEvents = report.events.filter(event => event.occurredAt !== null).length
  const passed = matchesConfiguredMarker(selectedLeads)

  function toggleLead(id: SyntheticLeadId) {
    if (submitted) return
    setSelectedLeads(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  }

  if (view === 'drill') {
    return (
      <Shell disclaimer={labels.disclaimer}>
        <button className={styles.inlineBack} onClick={() => setView('replay')} type="button">
          <ArrowLeft aria-hidden="true" size={18} /> Back to pathway
        </button>
        <header className={styles.drillHeader}>
          <p className={styles.eyebrow}>CONTROLLED TRAINING · {report.training.durationMinutes} MIN</p>
          <h1>Door-to-ECG acquisition drill</h1>
          <p>Inspect a deterministic synthetic waveform, identify the configured marker, and verify the evidence needed for a traceable acquisition event.</p>
        </header>

        <section className={styles.drillPanel} aria-labelledby="waveform-title">
          <div className={styles.sectionHeading}>
            <h2 id="waveform-title">Synthetic ECG workspace</h2>
            <span><Activity aria-hidden="true" size={16} /> Generated by SVG engine</span>
          </div>
          <p className={styles.instructions}>Select every lead containing the configured post-QRS elevation marker. This is a controlled visual-recognition task, not ECG diagnosis.</p>
          <div className={styles.ecgGrid}>
            {DOOR_TO_ECG_SYNTHETIC_LEADS.map(lead => {
              const selected = selectedLeads.includes(lead.id)
              const resultClass = submitted && lead.configuredMarker ? styles.correctLead : submitted && selected ? styles.incorrectLead : ''
              return (
                <button
                  aria-label={`${lead.accessibleSummary} ${selected ? 'Selected.' : 'Not selected.'}`}
                  aria-pressed={selected}
                  className={`${styles.ecgLead} ${selected ? styles.selectedLead : ''} ${resultClass}`}
                  key={lead.id}
                  onClick={() => toggleLead(lead.id)}
                  type="button"
                >
                  <span>{lead.label}</span>
                  <svg aria-hidden="true" preserveAspectRatio="none" role="img" viewBox="0 0 640 108">
                    <path className={styles.ecgTrace} d={lead.path} />
                  </svg>
                </button>
              )
            })}
          </div>

          <div className={styles.evidenceChecklist}>
            <h3>Acquisition evidence checklist</h3>
            <ul>
              <li><CheckCircle2 aria-hidden="true" size={17} /> Source timestamp captured: 08:12</li>
              <li><CheckCircle2 aria-hidden="true" size={17} /> Synthetic record provenance: SIM-ECG</li>
              <li><CheckCircle2 aria-hidden="true" size={17} /> Waveform is readable at review scale</li>
            </ul>
          </div>

          {!submitted ? (
            <button className={styles.primaryAction} disabled={selectedLeads.length === 0} onClick={() => setSubmitted(true)} type="button">Check selection</button>
          ) : passed ? (
            <div className={styles.resultSuccess} role="status">
              <CheckCircle2 aria-hidden="true" size={22} />
              <div><strong>Configured marker found</strong><span>{DOOR_TO_ECG_MARKER_LEADS.join(', ')} matched the deterministic answer key.</span></div>
              <button className={styles.primaryAction} onClick={() => { setDrillComplete(true); setView('reassessment') }} type="button">Open reassessment</button>
            </div>
          ) : (
            <div className={styles.resultWarning} role="alert">
              <ShieldAlert aria-hidden="true" size={22} />
              <div><strong>Selection needs review</strong><span>Compare the segment immediately after the QRS complex across all four synthetic leads.</span></div>
              <button className={styles.secondaryAction} onClick={() => { setSelectedLeads([]); setSubmitted(false) }} type="button">Try again</button>
            </div>
          )}
        </section>
      </Shell>
    )
  }

  if (view === 'reassessment') {
    return (
      <Shell disclaimer={labels.disclaimer}>
        <button className={styles.inlineBack} onClick={() => setView('drill')} type="button">
          <ArrowLeft aria-hidden="true" size={18} /> Back to drill
        </button>
        <header className={styles.drillHeader}>
          <p className={styles.eyebrow}>REASSESSMENT · ILLUSTRATIVE ONLY</p>
          <h1>Re-run the same operational competency</h1>
          <p>The training result changes only the fictional replay. It does not alter the baseline record or claim a patient outcome.</p>
        </header>
        <section className={styles.reassessmentPanel} aria-labelledby="reassessment-title">
          <h2 id="reassessment-title">Door-to-ECG comparison</h2>
          <div className={styles.comparisonGrid}>
            <article><span>Baseline replay</span><strong>{report.metrics.elapsedMinutes} min</strong><small>Recorded synthetic interval</small></article>
            <article><span>Post-training simulation</span><strong>8 min</strong><small>Illustrative target run</small></article>
          </div>
          <div className={styles.reassessmentStatus}>
            <Clock3 aria-hidden="true" size={20} />
            <div><strong>Configured competency passed</strong><span>ECG acquisition evidence was recognized before the 10-minute demonstration threshold.</span></div>
          </div>
          <div className={styles.openGate}>
            <ShieldAlert aria-hidden="true" size={20} />
            <div><strong>Closure remains blocked</strong><span>The Cath Lab arrival timestamp is still missing and requires human review.</span></div>
          </div>
          <button className={styles.primaryAction} onClick={() => setView('replay')} type="button">Return to pathway replay</button>
        </section>
      </Shell>
    )
  }

  const integrityLabels: Record<ReplayIntegrityState, string> = {
    complete: 'Complete', delayed: `Delayed ${report.metrics.deltaMinutes ?? 0} min`, missing: 'Timestamp missing', conflict: 'Conflicting evidence',
  }

  return (
    <Shell disclaimer={labels.disclaimer}>
      <header className={styles.header}>
        <div>
          <p className={styles.eyebrow}>CLINIVERSE AI · BY NEURAOPS</p>
          <h1>{report.pathwayLabel}</h1>
          <p className={styles.subtitle}>Fictional simulation · Pathway {report.pathwayVersion} · Evidence review pending</p>
        </div>
        <div className={styles.headerActions}>
          <span className={`${styles.statusChip} ${styles.review}`}><span aria-hidden="true" />{labels.humanReview}</span>
          <Link className={styles.backLink} href="/">{labels.back}</Link>
        </div>
      </header>

      <section aria-labelledby="performance-title">
        <h2 id="performance-title">Pathway performance</h2>
        <div className={styles.kpiGrid}>
          <KpiCard label="Door to ECG" value={`${report.metrics.elapsedMinutes ?? '—'} min`} target={`Target ≤ ${report.metrics.targetMinutes} min`} status="At risk" tone="warning" fill={81} />
          <KpiCard label="Pathway completeness" value={`${report.metrics.completenessPercent}%`} target="Target 100%" status={`${measuredEvents} of ${report.events.length} measured`} tone="success" fill={report.metrics.completenessPercent} />
          <KpiCard label="Open safety gates" value={String(report.metrics.openSafetyGates)} target="Target 0 open" status="Closure blocked" tone="critical" fill={96} />
        </div>
      </section>

      <div className={styles.workspace}>
        <div>
          <section className={styles.timelinePanel} aria-labelledby="timeline-title">
            <div className={styles.sectionHeading}><h2 id="timeline-title">Event timeline</h2><span>{measuredEvents} of {report.events.length} measured</span></div>
            <ol className={styles.eventList}>
              {report.events.map(event => (
                <li className={styles.eventRow} key={event.id}>
                  <span className={`${styles.eventRail} ${styles[event.integrity]}`} aria-hidden="true" />
                  <div className={styles.eventBody}><strong>{event.label}</strong><span>{roleLabel(event.owner)} · {event.source.system}</span></div>
                  <div className={styles.eventMeta}><strong>{event.displayTime}</strong><span className={styles[event.integrity]}>{integrityLabels[event.integrity]}</span></div>
                </li>
              ))}
            </ol>
          </section>
          <section className={styles.actionCard} aria-labelledby="action-title">
            <p className={styles.eyebrow}>NEXT CONTROLLED ACTION</p>
            <h2 id="action-title">{report.training.label}</h2>
            <p>{drillComplete ? 'The drill is complete. Reassessment evidence is available for reviewer inspection.' : 'Inspect the synthetic waveform, verify acquisition evidence, then reassess the same configured competency.'}</p>
            <p className={styles.trainingMeta}>{report.training.durationMinutes}-minute fictional exercise · No diagnosis or treatment authority</p>
          </section>
        </div>
        <div>
          <section className={styles.gapCard} aria-labelledby="gap-title">
            <p className={styles.eyebrow}>WHY IT WAS FLAGGED</p>
            <h2 id="gap-title">Door to ECG exceeded target by {report.metrics.deltaMinutes} minutes</h2>
            <dl className={styles.definitionList}>
              <Definition label="Rule" value={`${report.gap.rule.label} · ${report.gap.rule.version}`} />
              <Definition label="Evidence" value={report.gap.evidenceIds.join(' → ')} />
              <Definition label="Owner" value={`${roleLabel(report.gap.owner)} · Human review required`} tone="warning" />
            </dl>
            <button className={styles.actionLink} onClick={() => setView(drillComplete ? 'reassessment' : 'drill')} type="button">
              {drillComplete ? 'Review reassessment' : 'Open ECG drill'}
            </button>
          </section>
          <section className={styles.agentsPanel} aria-labelledby="agents-title">
            <div className={styles.sectionHeading}><h2 id="agents-title">Six governed agents</h2><span>Deterministic · Network-free</span></div>
            <ol className={styles.agentList}>
              {report.agents.map((agent, index) => (
                <li className={styles.agentRow} key={agent.id}>
                  <span className={`${styles.agentIndex} ${styles[agent.state]}`}>{String(index + 1).padStart(2, '0')}</span>
                  <div><strong>{agent.label}</strong><span>{agent.output}</span></div>
                  <em className={styles[agent.state]}>{agentLabels[agent.state]}</em>
                </li>
              ))}
            </ol>
          </section>
        </div>
      </div>
    </Shell>
  )
}

function Shell({ children, disclaimer }: { children: React.ReactNode; disclaimer: string }) {
  return <main className={styles.shell}><div className={styles.page}>{children}<footer className={styles.disclaimer}>{disclaimer}</footer></div></main>
}

function KpiCard({ label, value, target, status, tone, fill }: { label: string; value: string; target: string; status: string; tone: 'success' | 'warning' | 'critical'; fill: number }) {
  return <article className={styles.kpiCard}><div><span>{label}</span><strong>{value}</strong></div><div className={styles.kpiTrack} aria-hidden="true"><span className={styles[tone]} style={{ width: `${Math.min(Math.max(fill, 0), 100)}%` }} /></div><div><small>{target}</small><em className={styles[tone]}>{status}</em></div></article>
}

function Definition({ label, value, tone }: { label: string; value: string; tone?: 'warning' }) {
  return <div className={styles.definition}><dt>{label}</dt><dd className={tone ? styles[tone] : undefined}>{value}</dd></div>
}

function roleLabel(role: string) {
  return ({ referring: 'ED team', coordination: 'Pathway coordination', cardiology: 'Cardiology', 'cath-lab': 'Cath Lab', quality: 'Quality lead' } as Record<string, string>)[role] ?? role
}
