/**
 * Cliniverse Ward — Seed / Mock data for Phase A UI
 * Safe to use while engine is being wired
 */

import type {
  CensusSummary,
  DepartmentMeta,
  LiveEvent,
  WardPatient,
} from "./types";

export const DEPARTMENTS: DepartmentMeta[] = [
  { id: "ed", label: "Emergency", icon: "🚨" },
  { id: "im", label: "Internal Med", icon: "🩺" },
  { id: "cards", label: "Cardiology", icon: "🫀" },
  { id: "surg", label: "Surgery", icon: "🔪" },
  { id: "peds", label: "Pediatrics", icon: "👶" },
  { id: "ob", label: "OB/GYN", icon: "🌸" },
  { id: "lab", label: "Laboratory", icon: "🧪" },
];

/** Initial snapshot — engine can replace/mutate later */
export const MOCK_PATIENTS: WardPatient[] = [
  {
    id: "w1",
    templateId: "stemi_anterior",
    name: "Hassan Al-Amri",
    age: 62,
    sex: "M",
    bed: "CCU-1",
    department: "cards",
    diagnosis: "Anterior STEMI — Post PCI Day 2",
    priority: "urgent",
    status: "in_treatment",
    assignedToMe: true,
    assignedTo: "local-user",
    admittedAt: "2026-08-11T08:00:00Z",
    expectedStayHours: 72,
    timeline: [
      {
        id: "t1",
        at: "2026-08-11T06:10:00Z",
        title: "ED arrival",
        detail: "Crushing chest pain 2h",
        type: "arrival",
      },
      {
        id: "t2",
        at: "2026-08-11T06:25:00Z",
        title: "ECG STEMI",
        detail: "Anterior ST elevation",
        type: "result",
      },
      {
        id: "t3",
        at: "2026-08-11T08:00:00Z",
        title: "Admitted CCU post PCI",
        type: "decision",
      },
    ],
    workup: [
      {
        id: "wu1",
        kind: "ecg",
        title: "12-lead ECG",
        status: "reviewed",
        summary: "Evolving anterior changes",
        critical: true,
      },
      {
        id: "wu2",
        kind: "troponin",
        title: "Troponin",
        status: "ready",
        summary: "Elevated",
        critical: true,
      },
    ],
    orders: [
      { id: "o1", label: "DAPT", status: "done" },
      { id: "o2", label: "Post-PCI monitoring", status: "pending" },
    ],
    consults: [],
  },
  {
    id: "w2",
    templateId: "stroke_ischemic",
    name: "Amira Saleh",
    age: 53,
    sex: "F",
    bed: "N-4B",
    department: "im",
    diagnosis: "Ischemic Stroke — MCA territory",
    priority: "critical",
    status: "awaiting_consult",
    assignedToMe: true,
    assignedTo: "local-user",
    admittedAt: "2026-08-12T02:00:00Z",
    expectedStayHours: 96,
    timeline: [
      {
        id: "t1",
        at: "2026-08-12T01:20:00Z",
        title: "ED arrival",
        detail: "Sudden right weakness",
        type: "arrival",
      },
    ],
    workup: [
      {
        id: "wu1",
        kind: "ct",
        title: "CT head",
        status: "ready",
        summary: "No hemorrhage",
        critical: true,
      },
    ],
    orders: [
      { id: "o1", label: "Swallow assessment", status: "pending" },
      { id: "o2", label: "Neuro checks q1h", status: "pending" },
    ],
    consults: [
      {
        id: "c1",
        fromDept: "im",
        toDept: "im",
        reason: "Stroke team / neuro input",
        status: "requested",
      },
    ],
  },
  {
    id: "w3",
    templateId: "dka",
    name: "Sarah Eid",
    age: 49,
    sex: "F",
    bed: "M-2C",
    department: "im",
    diagnosis: "Diabetic Ketoacidosis",
    priority: "urgent",
    status: "awaiting_orders",
    assignedToMe: true,
    assignedTo: "local-user",
    admittedAt: "2026-08-12T04:30:00Z",
    expectedStayHours: 36,
    timeline: [],
    workup: [
      {
        id: "wu1",
        kind: "chem",
        title: "Chemistry + glucose",
        status: "ready",
        summary: "High glucose · anion gap",
        critical: true,
      },
    ],
    orders: [
      { id: "o1", label: "IV fluids", status: "pending" },
      { id: "o2", label: "Insulin protocol", status: "pending" },
    ],
    consults: [],
  },
  {
    id: "w4",
    templateId: "cap_severe",
    name: "Layla Khalid",
    age: 41,
    sex: "F",
    bed: "R-3A",
    department: "im",
    diagnosis: "Community Acquired Pneumonia",
    priority: "stable",
    status: "in_treatment",
    assignedToMe: false,
    admittedAt: "2026-08-11T14:00:00Z",
    expectedStayHours: 48,
    timeline: [],
    workup: [
      {
        id: "wu1",
        kind: "cxr",
        title: "Chest X-ray",
        status: "reviewed",
        summary: "RLL infiltrate",
      },
    ],
    orders: [{ id: "o1", label: "IV antibiotics", status: "done" }],
    consults: [],
  },
  {
    id: "w5",
    templateId: "stemi_anterior",
    name: "Yusuf Mansour",
    age: 34,
    sex: "M",
    bed: "ED-7",
    department: "ed",
    diagnosis: "Chest pain — R/O ACS",
    priority: "urgent",
    status: "workup_pending",
    assignedToMe: false,
    admittedAt: "2026-08-12T07:00:00Z",
    expectedStayHours: 24,
    timeline: [],
    workup: [
      { id: "wu1", kind: "ecg", title: "ECG", status: "pending" },
      { id: "wu2", kind: "troponin", title: "Troponin", status: "pending" },
    ],
    orders: [],
    consults: [],
  },
  {
    id: "w6",
    templateId: "preeclampsia",
    name: "Nora Al-Rashidi",
    age: 28,
    sex: "F",
    bed: "OB-2",
    department: "ob",
    diagnosis: "Pre-eclampsia — 34 weeks",
    priority: "critical",
    status: "awaiting_orders",
    assignedToMe: false,
    admittedAt: "2026-08-12T05:00:00Z",
    expectedStayHours: 48,
    timeline: [],
    workup: [
      {
        id: "wu1",
        kind: "chem",
        title: "LFTs / creatinine",
        status: "ready",
        critical: true,
      },
    ],
    orders: [{ id: "o1", label: "OB senior review", status: "pending" }],
    consults: [],
  },
  {
    id: "w7",
    templateId: "postop_ulcer",
    name: "Omar Faris",
    age: 71,
    sex: "M",
    bed: "S-1B",
    department: "surg",
    diagnosis: "Perforated peptic ulcer — Post-op Day 1",
    priority: "urgent",
    status: "in_treatment",
    assignedToMe: true,
    assignedTo: "local-user",
    admittedAt: "2026-08-11T20:00:00Z",
    expectedStayHours: 72,
    timeline: [],
    workup: [],
    orders: [{ id: "o1", label: "IV antibiotics", status: "done" }],
    consults: [],
  },
];

export const MOCK_CENSUS: CensusSummary = {
  date: new Date().toISOString().slice(0, 10),
  seen: 7,
  assigned: 4,
  discharged: 2,
  consultsRequested: 1,
  consultsGiven: 0,
  criticalHandled: 2,
  xpEarned: 180,
};

export const MOCK_LIVE_EVENTS: LiveEvent[] = [
  {
    id: "e1",
    type: "admitted",
    label: "Hassan Al-Amri → CCU",
    time: "08:00",
    at: "2026-08-12T08:00:00Z",
    patientId: "w1",
  },
  {
    id: "e2",
    type: "critical",
    label: "Amira Saleh — NEW imaging result",
    time: "09:14",
    at: "2026-08-12T09:14:00Z",
    patientId: "w2",
  },
  {
    id: "e3",
    type: "discharged",
    label: "Bed N-3C cleared",
    time: "09:30",
    at: "2026-08-12T09:30:00Z",
  },
  {
    id: "e4",
    type: "admitted",
    label: "Yusuf Mansour → ED-7",
    time: "10:05",
    at: "2026-08-12T10:05:00Z",
    patientId: "w5",
  },
  {
    id: "e5",
    type: "transfer",
    label: "ICU → Ward transfer logged",
    time: "10:22",
    at: "2026-08-12T10:22:00Z",
  },
];
