import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test.beforeEach(async ({ page }, info) => {
  await page.goto('/labs/work-preview')
  if (info.project.name === 'large-text') await page.addStyleTag({ content: 'html { font-size: 24px !important; }' })
})
test('source, explicit review and receipt remain review-only; keyboard back restores focus', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await expect(page.getByRole('heading', { name: 'What changed' })).toBeVisible()
  await page.getByRole('button', { name: 'Synthetic source change' }).click()
  await page.getByRole('button', { name: 'Back to changes' }).click()
  await expect(page.getByRole('button', { name: 'Synthetic source change' })).toBeFocused()
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Open source evidence' }).click()
  await expect(page.getByText('Synthetic evidence only. No patient data.')).toBeVisible()
  await page.getByRole('button', { name: 'Record my review' }).click()
  await expect(page.getByRole('heading', { name: 'Review recorded' })).toBeVisible()
  await expect(page.getByText('The clinical task remains open.')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const accessibility = await new AxeBuilder({ page }).include('main').analyze()
  expect(accessibility.violations).toEqual([])
  expect(errors).toEqual([])
  await page.screenshot({ path: `test-results/work-receipt-${info.project.name}.png`, fullPage: true })
})
test('uncertain outcome reconciles; revoked and stale scenarios cannot claim success', async ({ page }, info) => {
  test.skip(info.project.name !== 'desktop', 'one adverse-scenario pass; layout covered separately')
  await page.getByLabel('Scenario').selectOption('timeout-after-commit')
  await page.getByRole('button', { name: 'Synthetic source change' }).click()
  await page.getByRole('button', { name: 'Open source evidence' }).click()
  await page.getByRole('button', { name: 'Record my review' }).click()
  await expect(page.getByRole('heading', { name: 'Review outcome uncertain' })).toBeVisible()
  await page.getByRole('button', { name: 'Check review outcome' }).click()
  await expect(page.getByRole('heading', { name: 'Review recorded' })).toBeVisible()
  await page.getByLabel('Scenario').selectOption('revoked')
  await expect(page.getByRole('heading', { name: 'Institution access unavailable' })).toBeVisible()
  await expect(page.getByText('Synthetic evidence only. No patient data.')).toHaveCount(0)
  await page.getByLabel('Scenario').selectOption('stale')
  await page.getByRole('button', { name: 'Synthetic source change' }).click()
  await page.getByRole('button', { name: 'Open source evidence' }).click()
  await page.getByRole('button', { name: 'Record my review' }).click()
  await expect(page.getByRole('heading', { name: 'Review needs a fresh source' })).toBeVisible()
})
test('offline hides source and retry stays masked until reconnection', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'desktop', 'lifecycle checked once')
  await page.getByRole('button', { name: 'Synthetic source change' }).click()
  await page.getByRole('button', { name: 'Open source evidence' }).click()
  await expect(page.getByText('Synthetic evidence only. No patient data.')).toBeVisible()
  await context.setOffline(true)
  await expect(page.getByRole('heading', { name: 'Institution access unavailable' })).toBeVisible()
  await page.getByRole('button', { name: 'Check access again' }).click()
  await expect(page.getByText('Synthetic evidence only. No patient data.')).toHaveCount(0)
  await context.setOffline(false)
  await expect(page.getByRole('button', { name: 'Synthetic source change' })).toBeVisible()
})
