/** Editorial microcase drafts. Source discovery is not clinical attestation. */
export interface CasePreview {
  id: string
  title: string
  track: 'ECG' | 'Echo' | 'Integrated'
  objective: string
  scenario: string
  question: string
  options: string[]
  answer: number
  explanation: string
  communication: string
  sourceIds: string[]
  legacyOrigins: string[]
  status: 'draft'
  clinicalReview: 'user-confirmed'
  mediaStatus: 'unbound'
}

export const sourceRegistry: Record<string, { title: string; url: string; scope: string }> = {
  acs: { title: 'ESC 2023 · Acute coronary syndromes', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/acute-coronary-syndromes/', scope: 'Guideline landing page verified; claim-level review pending.' },
  mi: { title: 'ESC 2026 · Fifth universal definition of MI', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/universal-definition-myocardial-infarction/', scope: 'New definition located; reconcile full text before approval.' },
  hf: { title: 'ESC guideline directory · Heart failure 2026', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/', scope: '2026 update listed; direct guideline retrieval failed. Full-text review pending.' },
  bp: { title: 'ESC 2024 · Elevated blood pressure and hypertension', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/elevated-blood-pressure-and-hypertension/', scope: 'Guideline identified; claim-level review pending.' },
  af: { title: 'ESC 2024 · Atrial fibrillation', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/atrial-fibrillation/', scope: 'Guideline landing page verified; rhythm criteria and explanation review pending.' },
  svt: { title: 'ESC guideline directory · Supraventricular tachycardia', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/', scope: '2019 topic listed; direct full-text retrieval pending.' },
  pacing: { title: 'ESC 2021 · Cardiac pacing', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/cardiac-pacing-and-cardiac-resynchronization-therapy/', scope: 'Guideline landing page verified; claim-level review pending.' },
  va: { title: 'ESC 2022 · Ventricular arrhythmias', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/ventricular-arrhythmias-and-the-prevention-of-sudden-cardiac-death/', scope: 'Guideline landing page verified; claim-level review pending.' },
  cm: { title: 'ESC 2023 · Cardiomyopathies', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/cardiomyopathy/', scope: 'Guideline landing page verified; claim-level review pending.' },
  valves: { title: 'ESC/EACTS 2025 · Valvular heart disease', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/valvular-heart-disease/', scope: 'Guideline landing page verified; claim-level review pending.' },
  right: { title: 'ASE 2025 · Right heart assessment', url: 'https://www.asecho.org/wp-content/uploads/2025/03/PIIS0894731725000379.pdf', scope: 'Primary document located; supports multi-view, multiparameter assessment. Per-case attestation pending.' },
  diastolic: { title: 'ASE 2025 · LV diastolic function', url: 'https://www.asecho.org/wp-content/uploads/2025/07/Left-Ventricular-Diastolic-Function.pdf', scope: 'Primary document opened; per-case claim mapping and attestation pending.' },
  pericardial: { title: 'ESC 2025 · Myocarditis and pericarditis', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/myocarditis-and-pericarditis/', scope: 'Guideline landing page verified; claim-level review pending.' },
}

type Seed = [string, string, CasePreview['track'], string, string, string, string[], number, string, string, string[], string[]]
const seeds: Seed[] = [
  ['anterior-stemi', 'Anterior STEMI', 'ECG', 'Describe regional ST changes and prioritise escalation.', 'A fictional adult has ongoing central chest discomfort. A written ECG report describes ST elevation in V1–V4 with reciprocal inferior changes.', 'Which interpretation best fits this description?', ['A normal ECG', 'An anterior acute coronary occlusion pattern requiring urgent assessment', 'A diagnosis excluded by a single normal troponin'], 1, 'Regional ST elevation with compatible symptoms raises concern for acute coronary occlusion. The full tracing and clinical context are essential; do not wait for a biomarker result to recognise a concerning pattern.', 'Explain why the team needs to assess the tracing promptly.', ['acs','mi'], ['app/components/ClinicalLibrary.tsx#c1','app/lib/ward/templates.ts#stemi_anterior']],
  ['non-st-elevation', 'Chest pain without ST elevation', 'ECG', 'Recognise the limits of one ECG.', 'A fictional patient reports recurrent chest discomfort. The initial written ECG description has no ST elevation; serial biomarker results are not yet available.', 'What can this first ECG establish?', ['It excludes ACS', 'It proves a non-cardiac cause', 'It does not alone exclude ACS'], 2, 'An initial ECG without ST elevation does not settle the cause of chest pain. Clinical assessment, repeat ECGs when appropriate and serial biomarkers contribute to evaluation.', 'Explain why additional assessment can be needed despite the first ECG.', ['acs','mi'], []],
  ['acute-heart-failure', 'Acute heart failure', 'Integrated', 'Connect congestion symptoms with cardiac assessment.', 'A fictional adult with known reduced LV function has worsening breathlessness, orthopnoea and ankle swelling. No new cine is supplied.', 'Which review is most relevant?', ['Congestion, perfusion and possible precipitants together', 'Only the old EF number', 'Only the ankle swelling'], 0, 'The presentation needs a whole-patient assessment. An old EF does not describe current perfusion, congestion or the precipitating problem. Treatment details require the current guideline and clinical review.', 'Ask the patient to describe the change from their usual breathing.', ['hf'], ['app/components/ClinicalLibrary.tsx#c2']],
  ['hypertensive-emergency', 'Severe BP with organ injury', 'Integrated', 'Distinguish a number from evidence of acute organ injury.', 'A fictional adult has severely elevated BP with new confusion and acute kidney injury. The old case also describes LVH.', 'What changes the urgency of this presentation?', ['LVH alone', 'Evidence of new organ injury', 'The absence of chest pain excludes urgency'], 1, 'Acute organ injury is central to evaluating a possible hypertensive emergency. LVH can reflect chronic pressure loading and does not by itself establish an acute emergency.', 'Explain why the neurological and kidney findings matter.', ['bp'], ['app/components/ClinicalLibrary.tsx#c3']],
  ['atrial-fibrillation', 'Atrial fibrillation', 'ECG', 'Describe rhythm before naming it.', 'A fictional tracing description reports irregular RR intervals with no consistent discrete P waves.', 'Which rhythm is suggested?', ['Regular sinus rhythm', 'Atrial fibrillation', 'Complete AV block proven by this description'], 1, 'This description suggests AF. Confirm on an adequate ECG and interpret alongside symptoms; rhythm recognition alone does not determine anticoagulation or rate-control treatment.', 'Explain that recognising a rhythm is one part of the assessment.', ['af'], []],
  ['atrial-flutter', 'Atrial flutter', 'ECG', 'Separate atrial activity from ventricular rate.', 'A fictional ECG description reports organised repeating atrial activity and a regular ventricular response. The atrial rate is faster than the ventricular rate.', 'What should be inspected next?', ['Only the automated rhythm label', 'Assume all regular tachycardia is sinus', 'Atrial morphology and the atrioventricular relationship'], 2, 'Organised atrial activity can suggest flutter or another atrial tachycardia. Inspect the actual atrial pattern and conduction relationship rather than inferring a rhythm from ventricular rate alone.', 'Describe that the upper and lower chambers may be beating at different rates.', ['svt'], []],
  ['regular-narrow-tachycardia', 'Regular narrow-complex tachycardia', 'ECG', 'Describe a tachycardia without overcalling its mechanism.', 'A fictional patient has palpitations. The report describes a regular narrow-complex tachycardia, without clearly described atrial activity.', 'Which conclusion is justified?', ['The precise mechanism is certain', 'Further ECG and clinical assessment are needed', 'A narrow QRS proves the patient is stable'], 1, 'QRS width and regularity are a starting description. They do not alone distinguish all supraventricular mechanisms or establish haemodynamic stability.', 'Ask about symptoms while explaining that the rhythm needs closer assessment.', ['svt'], []],
  ['complete-av-block', 'AV dissociation and bradycardia', 'ECG', 'Inspect the relationship between P waves and QRS complexes.', 'A fictional tracing description reports regular P waves and a slower regular QRS rhythm, with no fixed relationship between them.', 'What is the key observation?', ['A constant PR interval', 'A normal sinus rhythm', 'Atrial and ventricular activity are dissociated'], 2, 'Independent atrial and ventricular activity requires careful evaluation for complete AV block and other causes of AV dissociation. A description alone is not a pacing prescription.', 'Explain why a slow pulse with symptoms needs prompt assessment.', ['pacing'], []],
  ['wide-complex-tachycardia', 'Wide-complex tachycardia', 'ECG', 'Recognise diagnostic uncertainty in a potentially dangerous rhythm.', 'A fictional adult has palpitations with a sustained regular wide-complex tachycardia on the ECG report.', 'What is the safest interpretive statement?', ['A potentially serious rhythm needs urgent expert assessment', 'It is harmless because it is regular', 'It is definitely SVT from QRS width alone'], 0, 'Wide-complex tachycardia has important differential diagnoses, including VT. Assess the patient and the full ECG urgently; do not label it benign from regularity alone.', 'Explain the need for monitoring and immediate clinical assessment.', ['va'], []],
  ['qt-review', 'QT interval and context', 'ECG', 'Recognise when automated QT measurements need review.', 'A fictional ECG machine flags a prolonged QTc. The tracing is noisy and the medication list has not been checked.', 'What review is needed?', ['Accept the automated value without inspection', 'Review the tracing, correction method, medicines and electrolytes', 'Use heart rate alone to diagnose a congenital syndrome'], 1, 'QT interpretation depends on measurement quality and clinical context. An automated flag should trigger review rather than a definitive syndrome label.', 'Explain why the team is checking both the tracing and medicines.', ['va'], []],
  ['hyperkalaemia', 'Potassium and ECG changes', 'ECG', 'Use ECG and laboratory context together.', 'A fictional patient with kidney injury has an elevated potassium result. The ECG description is initially unremarkable.', 'Does that ECG exclude risk from hyperkalaemia?', ['Yes, always', 'Yes, if the patient has no chest pain', 'No; ECG appearance alone cannot exclude clinically important hyperkalaemia'], 2, 'The laboratory result, sample quality and clinical context need prompt assessment. Do not dismiss significant hyperkalaemia because an ECG description appears normal. A dedicated current potassium-management source is still needed for this draft.', 'Explain why the blood result still needs attention.', ['va'], ['app/lib/ward/wardTemplatesExtra.ts#aki_severe']],
  ['a4c-orientation', 'Apical four-chamber orientation', 'Echo', 'Identify what must be visible before interpreting an A4C view.', 'An editorial exercise asks you to plan review of an apical four-chamber cine. No approved cine is attached to this draft.', 'What should the reviewer establish first?', ['View orientation, chamber landmarks and image quality', 'A diagnosis from the filename', 'EF from a single still frame'], 0, 'Identify the view and assess image quality before interpretation. This text exercise cannot substitute for cine-based recognition or a measurement assessment.', 'Explain that image quality affects what the examination can show.', ['right'], []],
  ['dilated-lv', 'Dilated LV phenotype', 'Echo', 'Separate a phenotype from its cause.', 'A fictional echo report describes a dilated LV with global systolic impairment. There is no clinical history or coronary assessment attached.', 'What can be concluded?', ['The cause is definitely genetic', 'The phenotype is described, but the cause needs further assessment', 'Coronary disease is excluded'], 1, 'Chamber dilation and impaired function describe a phenotype. Determining its cause requires clinical context and further assessment. Existing DCM media are not automatically bound to this case.', 'Explain the difference between how the heart looks and why it changed.', ['cm','hf'], []],
  ['hypertrophic-phenotype', 'Increased LV wall thickness', 'Echo', 'Recognise the differential behind a thickened LV.', 'A fictional report describes increased LV wall thickness. Blood-pressure history, loading conditions and family history are not supplied.', 'Which conclusion is appropriate?', ['HCM is proven from thickness alone', 'It is always athletic adaptation', 'The finding needs clinical and imaging context'], 2, 'Increased wall thickness is not a complete etiological diagnosis. Review loading conditions, family history and the broader imaging findings before classification.', 'Ask about family history and explain why more context is needed.', ['cm'], []],
  ['aortic-stenosis', 'Aortic stenosis: integrated assessment', 'Echo', 'Avoid grading a valve from one isolated observation.', 'A fictional echo description notes restricted aortic valve opening. Doppler measurements and flow context are not supplied.', 'Can severity be confidently graded?', ['No; integrated measurements and clinical context are needed', 'Yes, from the appearance alone', 'Yes, from the murmur volume alone'], 0, 'Valve assessment combines anatomy with haemodynamic measurements and context. A visual description alone does not establish the severity or an intervention plan.', 'Explain why additional measurements are needed.', ['valves'], []],
  ['mitral-regurgitation', 'Mitral regurgitation: beyond jet size', 'Echo', 'Use multiple findings when assessing regurgitation.', 'A fictional report describes a large colour Doppler mitral jet without documenting settings or quantitative findings.', 'Which approach is appropriate?', ['Grade solely from jet area', 'Integrate valve mechanism and multiple severity parameters', 'Ignore the valve because EF is preserved'], 1, 'Colour appearance is influenced by acquisition and haemodynamics. Assess mechanism and complementary parameters rather than using jet size alone.', 'Explain why the colour image is only one part of the report.', ['valves'], []],
  ['diastolic-function', 'Diastolic function assessment', 'Echo', 'Recognise the need for a multiparameter assessment.', 'A fictional patient has breathlessness and preserved EF. A single mitral inflow measurement is available.', 'What is a reasonable interpretation?', ['Preserved EF excludes heart failure', 'One measurement proves the diagnosis', 'More clinical and echocardiographic information is needed'], 2, 'Preserved EF alone does not settle the cause of breathlessness. Diastolic assessment integrates measurements and clinical context; do not diagnose from one value.', 'Explain that pumping fraction is not the whole assessment of heart function.', ['diastolic','hf'], []],
  ['rv-strain', 'RV strain and suspected PE', 'Echo', 'Separate right-heart findings from a definitive cause.', 'A fictional patient has acute dyspnoea. The written echo report describes RV dilation and reduced RV function; no diagnostic pulmonary imaging is supplied.', 'What does this establish?', ['PE is proven by RV dilation alone', 'Right-heart abnormalities that require contextual assessment', 'A normal pulmonary circulation'], 1, 'RV abnormalities can arise from more than one cause. They may contribute to assessment but do not independently prove PE. A dedicated current PE diagnostic source remains a review requirement.', 'Explain why the team may need other tests to identify the cause.', ['right'], ['app/components/ClinicalLibrary.tsx#r1','app/components/DiagnosticDetective.tsx#mystery_chest']],
  ['pericardial-effusion', 'Pericardial effusion and physiology', 'Echo', 'Distinguish fluid presence from haemodynamic effect.', 'A fictional echo report describes pericardial fluid. Blood pressure, chamber-collapse timing and Doppler findings are not available.', 'Can tamponade be determined from fluid presence alone?', ['No; clinical and physiological assessment is needed', 'Yes, any fluid proves tamponade', 'No fluid collection ever causes compromise'], 0, 'The presence of fluid is distinct from its physiological impact. Integrate clinical status and relevant echo findings when assessing possible tamponade.', 'Explain why the effect on circulation matters as well as the fluid.', ['pericardial'], []],
  ['echo-quality', 'Echo quality and uncertainty', 'Echo', 'State when the evidence is insufficient.', 'A fictional study has a foreshortened apical view and incomplete endocardial definition. A precise EF is requested.', 'What should the report communicate?', ['A precise number despite inadequate images', 'Certainty because the study contains a cine', 'Image limitations and the need for better assessment'], 2, 'Communicate acquisition limitations and avoid unsupported precision. Further suitable imaging or optimisation may be needed. A comprehensive acquisition/quantification source is still required for approval.', 'Explain what could and could not be assessed reliably.', ['right'], []],
]

export const batch20: CasePreview[] = seeds.map(([id,title,track,objective,scenario,question,options,answer,explanation,communication,sourceIds,legacyOrigins]) => ({
  id,title,track,objective,scenario,question,options,answer,explanation,communication,sourceIds,legacyOrigins,
  status: 'draft', clinicalReview: 'user-confirmed', mediaStatus: 'unbound',
}))
export const batchReview = { checkedAt: '2026-09-14', userConfirmedTextCases: 20, sourceReview: 'discovery-only', reviewer: 'project-owner-confirmation', scope: 'text-only; does not approve media or release readiness' } as const
